# Generated by Django 4.1.5 on 2023-01-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(default="hqdefault.jpg", upload_to="images/"),
        ),
    ]
