# Generated by Django 4.1.5 on 2023-01-18 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0002_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="commentary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course_app.comment",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="subscribers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
