# Generated by Django 4.1.5 on 2023-01-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0003_alter_course_commentary_alter_course_subscribers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(max_length=200),
        ),
    ]
