# Generated by Django 4.1.5 on 2023-01-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0004_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=20),
        ),
    ]
