# Generated by Django 4.1.5 on 2023-01-18 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0006_alter_course_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="subscribers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
