# Generated by Django 4.1.5 on 2023-01-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0008_alter_course_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="hqdefault.jpg", upload_to="images/"),
        ),
    ]
