# Generated by Django 4.1.5 on 2023-01-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0010_alter_course_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="category",
            new_name="categories",
        ),
    ]
