# Generated by Django 4.1.5 on 2023-01-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0011_rename_category_course_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="categories",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="course_app.category"
            ),
        ),
    ]
