# Generated by Django 4.1.5 on 2023-01-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0012_alter_course_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
