# Generated by Django 4.1.5 on 2023-01-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0013_lecture_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecture",
                to="course_app.course",
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="home_work",
            field=models.URLField(max_length=100),
        ),
    ]
