# Generated by Django 4.1.5 on 2023-01-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0015_remove_user_paid_course_user_course_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
