# Generated by Django 4.1.5 on 2023-01-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0016_comment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="commentary",
        ),
        migrations.AddField(
            model_name="course",
            name="commentary",
            field=models.ManyToManyField(
                blank=True, null=True, to="course_app.comment"
            ),
        ),
    ]
