# Generated by Django 4.1.5 on 2023-01-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0017_remove_course_commentary_course_commentary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="commentary",
        ),
        migrations.AddField(
            model_name="comment",
            name="commentary",
            field=models.ManyToManyField(blank=True, null=True, to="course_app.course"),
        ),
    ]
