# Generated by Django 4.1.5 on 2023-01-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0018_remove_course_commentary_comment_commentary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="commentary",
            new_name="course",
        ),
    ]
