# Generated by Django 4.1.5 on 2023-01-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0019_rename_commentary_comment_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="course",
        ),
        migrations.AddField(
            model_name="comment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course_app.course",
            ),
        ),
    ]
