# Generated by Django 4.1.5 on 2023-01-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0020_remove_comment_course_comment_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="course_paid",
            field=models.ManyToManyField(
                blank=True, related_name="user_course", to="course_app.course"
            ),
        ),
    ]
