# Generated by Django 4.1.5 on 2023-01-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0021_alter_user_course_paid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="subscribers",
        ),
        migrations.AddField(
            model_name="user",
            name="listened_lecture",
            field=models.ManyToManyField(blank=True, to="course_app.lecture"),
        ),
    ]
