# Generated by Django 4.1.5 on 2023-01-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0022_remove_course_subscribers_user_listened_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rework_lecture",
            field=models.ManyToManyField(
                blank=True, related_name="user_rework", to="course_app.lecture"
            ),
        ),
    ]
