# Generated by Django 4.1.5 on 2023-01-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0024_payment_homework"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="rework_lecture",
            field=models.ManyToManyField(
                blank=True, related_name="mentor_rework", to="course_app.lecture"
            ),
        ),
    ]
