# Generated by Django 4.1.5 on 2023-01-22 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0025_homework_rework_lecture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="rework_lecture",
        ),
    ]
